// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkSKnMr8AjOV_7WnJUuHXpEm5zDzRFkm8',
    appId: '1:1012135033129:web:438ac968148acb0d095f38',
    messagingSenderId: '1012135033129',
    projectId: 'flutter-firebase-4e4e8',
    authDomain: 'flutter-firebase-4e4e8.firebaseapp.com',
    storageBucket: 'flutter-firebase-4e4e8.firebasestorage.app',
    measurementId: 'G-G1XF1HDR2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvDRv-EokW47nSN-CXp_KHkLNbnenM8JI',
    appId: '1:1012135033129:android:8e72ec25f79d1507095f38',
    messagingSenderId: '1012135033129',
    projectId: 'flutter-firebase-4e4e8',
    storageBucket: 'flutter-firebase-4e4e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqJIhHBVv7mm9b3u05m-RIBoPGFCcGtGk',
    appId: '1:1012135033129:ios:3319f39ccd1d615d095f38',
    messagingSenderId: '1012135033129',
    projectId: 'flutter-firebase-4e4e8',
    storageBucket: 'flutter-firebase-4e4e8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqJIhHBVv7mm9b3u05m-RIBoPGFCcGtGk',
    appId: '1:1012135033129:ios:3319f39ccd1d615d095f38',
    messagingSenderId: '1012135033129',
    projectId: 'flutter-firebase-4e4e8',
    storageBucket: 'flutter-firebase-4e4e8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkSKnMr8AjOV_7WnJUuHXpEm5zDzRFkm8',
    appId: '1:1012135033129:web:0a8ecd13133b5041095f38',
    messagingSenderId: '1012135033129',
    projectId: 'flutter-firebase-4e4e8',
    authDomain: 'flutter-firebase-4e4e8.firebaseapp.com',
    storageBucket: 'flutter-firebase-4e4e8.firebasestorage.app',
    measurementId: 'G-6LWKSF8BXF',
  );

}